name: Lint Dockerfile
on: [push, pull_request, workflow_dispatch]

jobs:
  hadolint:
    runs-on: ubuntu-24.04

    steps:
      - name: Checkout code
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0

      - name: Run hadolint
        uses: hadolint/hadolint-action@2332a7b74a6de0dda2e2221d575162eba76ba5e5
        with:
          dockerfile: Dockerfile
