name: Lint Dockerfile
on: [push, pull_request, workflow_dispatch]

jobs:
  hadolint:
    runs-on: ubuntu-24.04

    steps:
      - name: Checkout code
        uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10

      - name: Run hadolint
        uses: hadolint/hadolint-action@2332a7b74a6de0dda2e2221d575162eba76ba5e5
        with:
          dockerfile: Dockerfile
