name: Lint Dockerfile
on: [push, pull_request, workflow_dispatch]

jobs:
  hadolint:
    runs-on: ubuntu-26.04

    steps:
      - name: Checkout code
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1

      - name: Run hadolint
        uses: hadolint/hadolint-action@2332a7b74a6de0dda2e2221d575162eba76ba5e5
        with:
          dockerfile: Dockerfile
